# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

components:

  # ── Rust crates (crates.io) ────────────────────────────────────────────────
  rust-sdk:
    tag_pattern: "^iggy-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: crates
    package: iggy

  rust-cli:
    tag_pattern: "^cli-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: crates
    package: iggy-cli

  rust-bench:
    tag_pattern: "^bench-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: crates
    package: iggy-bench

  # ── DockerHub images ───────────────────────────────────────────────────────
  rust-server:
    tag_pattern: "^server-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: dockerhub
    image: apache/iggy
    dockerfile: Dockerfile.ci
    platforms: ["linux/amd64", "linux/arm64"]

  rust-mcp:
    tag_pattern: "^mcp-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: dockerhub
    image: apache/iggy-mcp
    dockerfile: Dockerfile.mcp.ci
    platforms: ["linux/amd64", "linux/arm64"]

  rust-bench-dashboard:
    tag_pattern: "^bench-dashboard-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: dockerhub
    image: apache/iggy-bench-dashboard
    dockerfile: core/bench/dashboard/server/Dockerfile
    platforms: ["linux/amd64", "linux/arm64"]

  rust-connectors:
    tag_pattern: "^connectors-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: dockerhub
    image: apache/iggy-connect
    dockerfile: Dockerfile.connectors.ci
    platforms: ["linux/amd64", "linux/arm64"]

  web-ui:
    tag_pattern: "^web-ui-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: dockerhub
    image: apache/iggy-web-ui
    dockerfile: web/Dockerfile
    platforms: ["linux/amd64", "linux/arm64"]

  # ── Other SDKs ─────────────────────────────────────────────────────────────
  sdk-python:
    tag_pattern: "^python-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: pypi

  sdk-node:
    tag_pattern: "^node-sdk-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: npm

  sdk-java:
    tag_pattern: "^java-sdk-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: maven

  sdk-csharp:
    tag_pattern: "^csharp-sdk-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: nuget

  # ── Go (tag only, no registry publish) ─────────────────────────────────────
  sdk-go:
    tag_pattern: "^foreign/go/v([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: none
