# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

docker:
  linux: 
    - linux/amd64
    - linux/arm64
    # - linux/arm/v7
    # - linux/ppc64le
    # - linux/s390x
    # - linux/386
    # - linux/riscv64

binaries:
  rust-musl:
    - x86_64-unknown-linux-musl
    - aarch64-unknown-linux-musl
  
  rust-gnu:
    - x86_64-unknown-linux-gnu
    - aarch64-unknown-linux-gnu
  
  rust-windows:
    - x86_64-pc-windows-msvc
  
  rust-macos:
    - x86_64-apple-darwin
    - aarch64-apple-darwin

test-platforms:
  primary:
    - ubuntu-latest
  extended:
    - ubuntu-latest
    - windows-latest
    - macos-latest